spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopnest
    username: root
    password: MySql@2024

  jpa:
    hibernate:
      ddl-auto: update
      generate-ddl: true
    show-sql: true

server:
  port: 8080